---
# - name: Wait for port 6443 to become open on the host, don't start checking for 10 seconds
#   ansible.builtin.wait_for:
#     host: "{{ apiserver_loadbalancer_domain_name }}"
#     port: 6443
#     connect_timeout: 3
#     delay: 20
#     timeout: 60

- name: install Pod network
  become: yes
  become_user: "{{ ansible_user }}"
  shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml >> pod_setup.txt
  args:
    chdir: $HOME
    creates: pod_setup.txt