---
- hosts: bastion[0]
  gather_facts: False
  roles:
    - { role: bastion-ssh-config, tags: ["localhost", "bastion"] }

- hosts: kube_node
  gather_facts: True
  roles:
    - { role: containerd, tags: kube_node}
    - { role: kuber-node, tags: kube_node}

- hosts: kube_control_plane
  gather_facts: True
  roles:
    - { role: containerd, tags: kube_control_plane}
    - { role: kuber-node, tags: kube_control_plane}
