---

- name: Start the cluster
  shell: "kubeadm init --pod-network-cidr=10.244.0.0/16 --control-plane-endpoint {{ apiserver_loadbalancer_domain_name }}:6443 --upload-certs >> cluster.txt"
  args:
    chdir: $HOME
    creates: cluster.txt

- name: create .kube directory
  become: yes
  become_user: "{{ ansible_user }}"
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"




